### ISSUE TITLE
New Errors

### ISSUE THREAD

**Issue by Techno-Fox** [ba0f3/ssh2.nim#1]
So I'm trying out the new ssh2 library, and I got some errors. types.nim on line 19 changed Channel to libssh2.Channel. 

And now this. Nim version is latest (1.0.6). Now I got this error

.nimble/pkgs/ssh2-0.1.0/ssh2/sftp.nim(78, 20) Error: type mismatch: got <SftpHandle, ptr array[0..1023, char], int>
        ... but expected one of: 
        ... proc sftp_read(h: SftpHandle; buf: ptr cstring; bufMaxLen: int): cint
        ...   first type mismatch at position: 2
        ...   required type for buf: ptr cstring
        ...   but expression 'addr buffer' is of type: ptr array[0..1023, char]
        ... expression: sftp_read(handle, addr buffer, len(buffer))

P.S. I like the high level idea.

**Comment by ba0f3** [comment]
oh sorry, I made some changes on libssh2 too, I for got to commit it. be patient!

**Comment by ba0f3** [comment]
please update libssh2 by `nimble install libssh2` and try again, thanks!
