### ISSUE TITLE
REQUST[multiple SSH sessions]

### ISSUE THREAD

**Issue by nixfreak** [ba0f3/ssh2.nim#3]
Hello

The library is awesome , I'm trying to figure out how to connect to multiple SSH sessions. Everytime I try it only connects once. 
Would be great if you could share a sample or example how to do this.

**Comment by ba0f3** [comment]
Thank you for your interesting, can you post you code here?

**Comment by nixfreak** [comment]
`import asyncdispatch, ssh2, sysinfo                                                                                                                                        
                                                                                                                                                                           
proc main() {.async.} =                                                                                                                                                    
    var client = newSSHClient()                                                                                                                                            
    defer: client.disconnect()                                                                                                                                             
    await client.connect("127.0.0.1", "user",  password="xxxxxxxxxxxxxxxxxxxxxxxxxxxxx")                                                                                   
    #echo await client.execCommand("uname -a")                                                                                                                             
    echo "Machine Name: ", getMachineName()                                                                                                                                
    #asyncCheck main()                                                                                                                                                     
                                                                                                                                                                           
waitFor main()                                                                                                                                                             
#asyncCheck main()                                                                                                                                                         
                                                                                                                                                                           
                                                                                                                                                                           
                                                                                                                                                                           
proc main1() {.async.} =                                                                                                                                                   
  var client = newSSHClient()                                                                                                                                              
  defer: client.disconnect()                                                                                                                                               
  await client.connect("10.1.10.15", "user", password="xxxxx")                                                                                                            
  echo "Host Name: ", getHostName()                                                                                                                                        
  #echo  await client.execCommand("ip addr show enp0s3|grep -i inet")                                                                                                      
  #echo("")                                                                                                                                                                
  #echo  await client.execCommand("whoami")                                                                                                                                
  #echo  await client.execCommand("date")                                                                                                                                  
  #echo  await client.execCommand("id")                                                                                                                                    
  #asyncCheck main1()                                                                                                                                                      
                                                                                                                                                                           
waitFor main1()                                                                                                                                                            
#runForever()  `

**Comment by nixfreak** [comment]
Actually got it working now, sorry about that
